apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-sre-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-sre-app
  template:
    metadata:
      labels:
        app: my-sre-app
    spec:
      containers:
      - name: flask-container
        image: peopyo/my-sre-portfolio:ci
        imagePullPolicy: Always
        ports:
        - name: flask
          containerPort: 5000
        - name: prometheus
          containerPort: 8000
        env:
        - name: DEEPSEEK_API_KEY
          valueFrom:
            secretKeyRef:
              name: deepseek-api-key
              key: DEEPSEEK_API_KEY 
---
apiVersion: v1
kind: Service
metadata:
  name: my-sre-service
spec:
  type: NodePort
  selector:
    app: my-sre-app
  ports:
  - name: flask
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30000
  - name: prometheus
    protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30001
